pool:
  vmImage: 'Ubuntu 16.04'

variables:
  repository: "wk-j/issue-downloader"

steps:

- script: |
    dotnet tool install -g Cake.Tool
  displayName: "Install tools"

# -- BUILD

- script: ~/.dotnet/tools/dotnet-cake -target=Pack
  displayName: 'Build with cake'

# -- PUBLISH

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    packagesToPush: '.publish/*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: nuget.org